server:
  port: 8083

spring:
  application:
    name: gym-crm-stg

  datasource:
    url: jdbc:postgresql://localhost:5435/gymcrm_stg
    username: stg_sa
    password: stg_s3cr3t
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true  # could be false

  sql:
    init:
      mode: always
      data-locations: classpath:data-stg.sql

security:
  bruteforce:
    max-attempts: 3
    block-minutes: 5
  jwt:
    secret: ${JWT_SECRET:'this-is-a-very-long-32+chars-secret-key!!'}
    issuer: gym-crm
    access-token-minutes: 30
  cors:
    allowed-origins: "https://stg.app.gym-crm.com"

logging:
  level:
    root: WARN
    com.epam.gymcrm: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: true
